DELETE FROM `NOTICE_CONTENTS`
WHERE `PK_A` = 'A001';
DELETE FROM `NOTICE_CONTENTS`
WHERE `PK_A` = 'A002';
DELETE FROM `NOTICE_CONTENTS`
WHERE `PK_A` = 'A003';
DELETE FROM `NOTICE_CONTENTS`
WHERE `PK_A` = 'A004';
DELETE FROM `NOTICE_CONTENTS`
WHERE `PK_A` = 'A005';

DELETE FROM `NOTICE_VISITOR`
WHERE `FK_A` = 'A001';
DELETE FROM `NOTICE_VISITOR`
WHERE `FK_A` = 'A002';
DELETE FROM `NOTICE_VISITOR`
WHERE `FK_A` = 'A003';
DELETE FROM `NOTICE_VISITOR`
WHERE `FK_A` = 'A004';
DELETE FROM `NOTICE_VISITOR`
WHERE `FK_A` = 'A005';
