CREATE TABLE `NOTICES_CONTENTS` (
	`PK_A`	VARCHAR(50)	NOT NULL,
	`CONTENTS`	VARCHAR(1000)	NULL,
	`WRITER`	VARCHAR(50)	NULL
);

CREATE TABLE `NOTICE _VISITOR` (
	`Key`	VARCHAR(50)	NOT NULL,
	`FK_A`	VARCHAR(50)	NOT NULL,
	`VISITOR`	VARCHAR(50)	NULL
);

ALTER TABLE `NOTICES_CONTENTS` ADD CONSTRAINT `PK_NOTICES_CONTENTS` PRIMARY KEY (
	`PK_A`
);

ALTER TABLE `NOTICE _VISITOR` ADD CONSTRAINT `PK_NOTICE _VISITOR` PRIMARY KEY (
	`Key`,
	`FK_A`
);

ALTER TABLE `NOTICE _VISITOR` ADD CONSTRAINT `FK_NOTICES_CONTENTS_TO_NOTICE _VISITOR_1` FOREIGN KEY (
	`FK_A`
)
REFERENCES `NOTICES_CONTENTS` (
	`PK_A`
);

