CREATE TABLE `NOTICE_CONTENTS` (
	`PK_A`	VARCHAR(50)	NOT NULL,
	`CONTENTS`	VARCHAR(1000)	NULL,
	`WRITER`	VARCHAR(50)	NULL
);

CREATE TABLE `NOTICE_VISITOR` (
	`PK_B`	VARCHAR(50)	NOT NULL,
	`FK_A`	VARCHAR(50)	NOT NULL,
	`VISITOR`	VARCHAR(50)	NULL
);

ALTER TABLE `NOTICE_CONTENTS` ADD CONSTRAINT `PK_NOTICE_CONTENTS` PRIMARY KEY (
	`PK_A`
);

ALTER TABLE `NOTICE_VISITOR` ADD CONSTRAINT `PK_NOTICE_VISITOR` PRIMARY KEY (
	`PK_B`,
	`FK_A`
);

ALTER TABLE `NOTICE_VISITOR` ADD CONSTRAINT `FK_NOTICE_CONTENTS_TO_NOTICE_VISITOR_1` FOREIGN KEY (
	`FK_A`
)
REFERENCES `NOTICE_CONTENTS` (
	`PK_A`
);
