CREATE TABLE `CAR_INFO` (
	`PK_A`	VARCHAR(50)	NOT NULL,
	`CAR_NAME`	VARCHAR(50)	NULL,
	`PRODUCT_YEAR`	DECIMAL(4)	NULL,
	`COMPANY_NAME`	VARCHAR(50)	NULL
);

CREATE TABLE `OPTION_INFO` (
	`PK_B`	VARCHAR(50)	NOT NULL,
	`OPTION`	VARCHAR(50)	NULL
);

CREATE TABLE `CAR_OPTION` (
	`PK_C`	VARCHAR(50)	NOT NULL,
	`FK_A`	VARCHAR(50)	NOT NULL,
	`FK_B`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `CAR_INFO` ADD CONSTRAINT `PK_CAR_INFO` PRIMARY KEY (
	`PK_A`
);

ALTER TABLE `OPTION_INFO` ADD CONSTRAINT `PK_OPTION_INFO` PRIMARY KEY (
	`PK_B`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `PK_CAR_OPTION` PRIMARY KEY (
	`PK_C`,
	`FK_A`,
	`FK_B`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_CAR_INFO_TO_CAR_OPTION_1` FOREIGN KEY (
	`FK_A`
)
REFERENCES `CAR_INFO` (
	`PK_A`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_OPTION_INFO_TO_CAR_OPTION_1` FOREIGN KEY (
	`FK_B`
)
REFERENCES `OPTION_INFO` (
	`PK_B`
);

